spring.application.name=13-spring-boot-namedparameterjdbctemplate-callback

#standard keys
spring.datasource.url = jdbc:mysql:///spring
spring.datasource.username =root
spring.datasource.password = nikhilhayatpur@123