spring.application.name=06-spring-boot-plain-jdbc

#standard keys for db connection in springboot
spring.datasource.url = jdbc:mysql:///spring
spring.datasource.username = root
spring.datasource.password = nikhilhayatpur@123