spring.application.name=06-spring-boot-plain-jdbc

#standard keys for db connection in springboot
spring.datasource.url = jdbc:mysql:///spring
spring.datasource.username = root
spring.datasource.password = nikhilhayatpur@123

#specify the datasourse you want so if mutiple datasourse aea available so this to choose
spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource