spring.application.name=05-spring-boot-DI

#user defined prices
emp.info.name = nikhil
emp.info.eid =01

#arrey type property
emp.info.nickName= sher,pilot,nk


#list type property
emp.info.friendsNames= sheer,jayesh,pal


#Set type property
emp.info.phoneNumber= 7011752235,9810667877,9729940056


#map type property
emp.info.bankDetails.sbi=1234
emp.info.bankDetails.haryanaGramin=85556
emp.info.bankDetails.axis=7894


#refreance type
emp.info.company.title=sher.co
emp.info.company.location=gurugram
emp.info.company.size=100


#standard keys for db connection in springboot
spring.datasource.url = jdbc:mysql:///spring
spring.datasource.username = root
spring.datasource.password = root@123