spring.application.name=08-spring-boot-profile-app

#standard keys for db connection in springboot
spring.datasource.url = jdbc:mysql:///spring
spring.datasource.username = root
spring.datasource.password = nikhilhayatpur@123

#set the profile you want
#spring.profiles.active=uat